import "dotenv/config";
import { db } from "./index";
import { products, type NewProduct } from "./schema";

const SEED: NewProduct[] = [
  {
    name: "Apple MacBook Air M2 13.6\"",
    brand: "Apple",
    model: "MacBook Air M2 (2022)",
    price: 224999,
    originalPrice: 249999,
    condition: "NEW",
    stock: 4,
    processor: "Apple M2 chip, 8-core CPU",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    gpu: "Apple 8-core GPU",
    display: "13.6\" Liquid Retina, 500 nits",
    battery: "Up to 18 hours, 52.6Wh",
    description:
      "Box-packed MacBook Air M2 in Midnight finish. Featherlight, silent and insanely fast for office work, freelancing, coding and everyday use.\n\nFull box, charger and cable included. Activated and checked by the DLS lab before dispatch.",
    warranty: "1 Year Apple Pakistan Warranty",
    images: ["/images/laptop-silver.jpg"],
    featured: true,
  },
  {
    name: "Apple MacBook Pro 14\" M3 Pro",
    brand: "Apple",
    model: "MacBook Pro 14 (M3 Pro)",
    price: 489999,
    originalPrice: 529999,
    condition: "NEW",
    stock: 2,
    processor: "Apple M3 Pro, 11-core CPU",
    ram: "18GB Unified Memory",
    storage: "512GB SSD",
    gpu: "Apple 14-core GPU",
    display: "14.2\" Liquid Retina XDR, 120Hz ProMotion",
    battery: "Up to 18 hours, 70Wh",
    description:
      "The professional's choice — M3 Pro power for video editing, 3D work and heavy development workloads. Space Black, sealed box.\n\nBest price in Peshawar, guaranteed by DIGITAL LAPTOP.",
    warranty: "1 Year Apple Pakistan Warranty",
    images: ["/images/laptop-white.jpg", "/images/laptop-silver.jpg"],
    featured: true,
  },
  {
    name: "Dell XPS 15 9530 OLED Touch",
    brand: "Dell",
    model: "XPS 15 9530",
    price: 349999,
    originalPrice: 389999,
    condition: "LIKE_NEW",
    stock: 2,
    processor: "Intel Core i7-13700H (13th Gen)",
    ram: "16GB DDR5 4800MHz",
    storage: "1TB NVMe SSD",
    gpu: "NVIDIA RTX 4050 6GB",
    display: "15.6\" 3.5K OLED Touch, 100% DCI-P3",
    battery: "6–7 hrs real-world, 86Wh",
    description:
      "Flagship creator machine in 9.5/10 condition — barely used US import. OLED panel is perfect for design and color-critical work.\n\nWith original Dell 130W charger. Battery health 96% (report attached at shop).",
    warranty: "3 Months DLS Service Warranty",
    images: ["/images/laptop-creator.jpg"],
    featured: true,
  },
  {
    name: "HP Spectre x360 14 (2024)",
    brand: "HP",
    model: "Spectre x360 14-eu",
    price: 265000,
    originalPrice: null,
    condition: "EXCELLENT",
    stock: 2,
    processor: "Intel Core Ultra 7 155H",
    ram: "16GB LPDDR5x",
    storage: "1TB NVMe SSD",
    gpu: "Intel Arc Graphics",
    display: "14\" 2.8K OLED Touch, 360° convertible",
    battery: "7–8 hrs, 68Wh",
    description:
      "Premium 2-in-1 with stunning OLED touch display — folds into a tablet for note-taking and presentations. UK import, A+ grade.\n\nIncludes HP stylus and fast charger.",
    warranty: "3 Months DLS Service Warranty",
    images: ["/images/laptop-blue.jpg"],
    featured: true,
  },
  {
    name: "Lenovo ThinkPad X1 Carbon Gen 11",
    brand: "Lenovo",
    model: "X1 Carbon Gen 11",
    price: 235000,
    originalPrice: null,
    condition: "LIKE_NEW",
    stock: 3,
    processor: "Intel Core i7-1355U (13th Gen)",
    ram: "16GB LPDDR5",
    storage: "512GB NVMe SSD",
    gpu: "Intel Iris Xe",
    display: "14\" 2.2K IPS, anti-glare",
    battery: "8+ hrs, 57Wh",
    description:
      "The legendary business ultrabook — 1.1kg carbon fiber body, best-in-class keyboard, military-grade durability. Corporate off-lease unit in superb condition.",
    warranty: "3 Months DLS Service Warranty",
    images: ["/images/laptop-business.jpg"],
    featured: false,
  },
  {
    name: "ASUS ROG Strix G16 RTX 4060",
    brand: "ASUS",
    model: "ROG Strix G16 G614",
    price: 389999,
    originalPrice: 419999,
    condition: "NEW",
    stock: 3,
    processor: "Intel Core i7-13650HX",
    ram: "16GB DDR5 4800MHz",
    storage: "1TB NVMe Gen4 SSD",
    gpu: "NVIDIA RTX 4060 8GB (140W)",
    display: "16\" FHD+ 165Hz, 100% sRGB",
    battery: "90Wh, fast charge 0–50% in 30 min",
    description:
      "Box-packed gaming beast — runs GTA V, Valorant, Warzone and every modern title at high FPS. MUX switch + Advanced Optimus for maximum performance.\n\nFree Windows 11 Pro + driver setup by DLS with every gaming laptop.",
    warranty: "1 Year Local Warranty + DLS Support",
    images: ["/images/laptop-gaming.jpg", "/images/laptop-gaming-2.jpg"],
    featured: true,
  },
  {
    name: "MSI Katana 15 RTX 4050",
    brand: "MSI",
    model: "Katana 15 B13V",
    price: 274500,
    originalPrice: null,
    condition: "NEW",
    stock: 4,
    processor: "Intel Core i7-13620H",
    ram: "16GB DDR5",
    storage: "512GB NVMe SSD",
    gpu: "NVIDIA RTX 4050 6GB",
    display: "15.6\" FHD 144Hz",
    battery: "53.5Wh",
    description:
      "Best-value RTX gaming laptop in Peshawar right now. Cooler Boost 5 thermals, 4-zone RGB keyboard, upgradeable RAM & SSD.\n\nBox-packed with official warranty card.",
    warranty: "1 Year Local Warranty + DLS Support",
    images: ["/images/laptop-gaming-2.jpg"],
    featured: false,
  },
  {
    name: "Dell Latitude 5440 Business",
    brand: "Dell",
    model: "Latitude 5440",
    price: 118000,
    originalPrice: 139000,
    condition: "GOOD",
    stock: 6,
    processor: "Intel Core i5-1335U (13th Gen)",
    ram: "16GB DDR4",
    storage: "256GB NVMe SSD",
    gpu: "Intel Iris Xe",
    display: "14\" FHD IPS",
    battery: "4–5 hrs",
    description:
      "Solid corporate workhorse at a budget price — perfect for students, office work and online classes. Signs of previous use on lid; internally perfect.\n\nFresh Windows 11 + MS Office installed by DLS.",
    warranty: "1 Month DLS Service Warranty",
    images: ["/images/laptop-business.jpg"],
    featured: false,
  },
  {
    name: "HP EliteBook 840 G10",
    brand: "HP",
    model: "EliteBook 840 G10",
    price: 158500,
    originalPrice: null,
    condition: "EXCELLENT",
    stock: 3,
    processor: "Intel Core i7-1355U vPro",
    ram: "16GB DDR5",
    storage: "512GB NVMe SSD",
    gpu: "Intel Iris Xe",
    display: "14\" FHD IPS, low power",
    battery: "6–7 hrs",
    description:
      "Premium aluminum business machine with vPro security and crystal-clear 5MP webcam. A-grade UK corporate import, battery health above 90%.",
    warranty: "3 Months DLS Service Warranty",
    images: ["/images/laptop-white.jpg"],
    featured: false,
  },
  {
    name: "Lenovo Legion 5 Pro RTX 4070",
    brand: "Lenovo",
    model: "Legion Pro 5 16ARX8",
    price: 425000,
    originalPrice: 455000,
    condition: "NEW",
    stock: 2,
    processor: "AMD Ryzen 7 7745HX",
    ram: "32GB DDR5 5200MHz",
    storage: "1TB NVMe Gen4 SSD",
    gpu: "NVIDIA RTX 4070 8GB (140W)",
    display: "16\" WQXGA 240Hz, 500 nits",
    battery: "80Wh",
    description:
      "No-compromise gaming & streaming machine. 240Hz QHD panel, full-power RTX 4070, legendary Legion cooling. Box-packed, sealed.\n\nIdeal for gaming, AI workloads and 4K video editing.",
    warranty: "1 Year Local Warranty + DLS Support",
    images: ["/images/laptop-gaming-2.jpg", "/images/laptop-gaming.jpg"],
    featured: true,
  },
  {
    name: "Acer Swift Go 14 OLED",
    brand: "Acer",
    model: "Swift Go 14 SFG14",
    price: 172999,
    originalPrice: null,
    condition: "NEW",
    stock: 4,
    processor: "Intel Core Ultra 5 125H",
    ram: "16GB LPDDR5x",
    storage: "512GB NVMe SSD",
    gpu: "Intel Arc Graphics",
    display: "14\" 2.8K OLED, 90Hz",
    battery: "8+ hrs, 65Wh",
    description:
      "Ultra-portable with a gorgeous OLED panel and all-day battery — the perfect university and freelancing companion. 1.3kg only.",
    warranty: "1 Year Local Warranty + DLS Support",
    images: ["/images/laptop-thin.jpg"],
    featured: false,
  },
  {
    name: "HP Pavilion 15 (Budget King)",
    brand: "HP",
    model: "Pavilion 15-eg3",
    price: 96500,
    originalPrice: 115000,
    condition: "GOOD",
    stock: 5,
    processor: "Intel Core i5-1235U (12th Gen)",
    ram: "8GB DDR4 (upgradeable)",
    storage: "512GB NVMe SSD",
    gpu: "Intel Iris Xe",
    display: "15.6\" FHD IPS",
    battery: "3–4 hrs",
    description:
      "Best budget laptop under Rs. 100k — fast SSD, backlit keyboard and big display for office work, online classes and browsing.\n\nFree RAM upgrade advice — ask about our 16GB upgrade deal at the shop.",
    warranty: "1 Month DLS Service Warranty",
    images: ["/images/laptop-blue.jpg"],
    featured: false,
  },
];

async function main() {
  console.log("Seeding DIGITAL LAPTOP inventory...");
  await db.delete(products);
  await db.insert(products).values(SEED);
  console.log(`Seeded ${SEED.length} products.`);
  process.exit(0);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
